- name: install nginx repo
  sudo: yes
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present

- name: switch mainline nginx repo
  sudo: yes
  replace: dest=/etc/yum.repos.d/nginx.repo regexp='packages/centos' replace='packages/mainline/centos'

- name: install nginx
  sudo: yes
  yum: name=nginx state=latest
  notify: restart nginx

- name: copy nginx confing
  sudo: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0644
  notify: reload nginx

- name: create www directory
  sudo: yes
  file: path=/var/www state=directory mode=0755

- name: enable nginx
  sudo: yes
  service: name=nginx enabled=yes
